@startuml

interface API {
    + buscar(query:String): <<JSON>>
}

interface StockAPI {
    + getStock(id: long): int
}

interface RepoArticulos {
    + buscar(query:String): Collection<Articulo>
}

class Articulo {
    - id: long
    - descripcion: String
    - stock: int
}


API "conoce" ..> StockAPI
API "conoce" ..> RepoArticulos
API "utiliza" ..> Articulo
RepoArticulos "contiene" ..> "0..n  " Articulo

@enduml