@startuml

interface API {
    + buscar(query:String): <<JSON>>
    + comprar(id:long): bool
    + estaLogueado(): bool
}

interface LoginAPI {
    + getLoginUI(): <<html>>
    + login(user:String, pass:String): String
    + logout(token:String): bool
}

interface StockAPI {
    + getStock(id: long): int
    + hayStock(id: long, cantidad:int): bool
    + actualizarStock(id: long, cantidad: int): bool
}

interface RepoArticulos {
    + buscar(query:String): Collection<Articulo>
    + getArticulo(id: long): Articulo
}

class Articulo {
    - id: long
    - descripcion: String
    - stock: int
}

interface FacturacionAPI {
    + facturar(articulo:Articulo, cantidad:int): bool
}

interface BancoAPI {
    + validarTransaccion(...): bool
}

API --> LoginAPI
API --> StockAPI
API --> RepoArticulos
API --> FacturacionAPI
API --> BancoAPI
FacturacionAPI "usa" ..> Articulo
RepoArticulos "articulos" --> Articulo

@enduml