@startuml

actor Usuario
participant ":API"
participant ":LoginAPI"
participant ":Repositorio"
participant ":StockAPI"
'participant ":FacturacionAPI"
'participant ":BancoAPI"

Usuario -> ":API" : buscar()
":API" -> ":Repositorio" : buscar()
":API" <-- ":Repositorio" : resultadoBusqueda
":API" -> ":StockAPI" : getStock()
":API" <-- ":StockAPI" : stock
Usuario <-- ":API" : resultado busqueda


@enduml